name: 扫描issue来更新注册表

on:
  workflow_dispatch:

  # schedule:
  #   - cron: '0 */1 * * *'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Bun
        uses: oven-sh/setup-bun@v2

      - name: Scan
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |
          bun i --production --frozen-lockfile
          bun p scan