name: 监听issue

on:
  issues:
    types:
      - edited
      - labeled

permissions:
  contents: write
  issues: write

jobs:
  upsert:
    if: ${{ !github.event.issue.pull_request && contains(github.event.issue.labels.*.name, 'UpsertPlugin') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Bun
        uses: oven-sh/setup-bun@v2

      - name: Upsert
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |
          bun i --production --frozen-lockfile
          bun p upsert ${{ github.event.issue.number }}

          git config user.name "delta-comic-bot"
          git config user.email "delta-comic-bot@proton.me"

          git add ./pages
          git commit -m "ci: update plugins [skip ci]" || echo "no changes to commit"
          git push -qf "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref_name }}